# Generated by Django 4.1.1 on 2022-10-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedpassword',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storedpassword',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
